export enum PROVINCE_TYPE {
  SEOUL = 'SEOUL',
  GYEONGGIDO = 'GYEONGGIDO',
  INCHEON = 'INCHEON',
  GANGWONDO = 'GANGWONDO',
  CHUNGCHEONGBUKDO = 'CHUNGCHEONGBUKDO',
  CHUNGCHEONGNAMDO = 'CHUNGCHEONGNAMDO',
  DAEJEON = 'DAEJEON',
  SEJONG = 'SEJONG',
  JEOLLABUKDO = 'JEOLLABUKDO',
  JEOLLANAMDO = 'JEOLLANAMDO',
  GWANGJU = 'GWANGJU',
  GYEONGSANGBUKDO = 'GYEONGSANGBUKDO',
  GYEONGSANGNAMDO = 'GYEONGSANGNAMDO',
  BUSAN = 'BUSAN',
  DAEGU = 'DAEGU',
  ULSAN = 'ULSAN',
  JEJU = 'JEJU',
}

export const province = [
  { key: PROVINCE_TYPE.SEOUL, value: '서울', search: '서울' },
  { key: PROVINCE_TYPE.GYEONGGIDO, value: '경기도', search: '경기도' },
  { key: PROVINCE_TYPE.INCHEON, value: '인천', search: '인천' },
  { key: PROVINCE_TYPE.GANGWONDO, value: '강원도', search: '강원도' },
  { key: PROVINCE_TYPE.CHUNGCHEONGBUKDO, value: '충북', search: '충청북도' },
  { key: PROVINCE_TYPE.CHUNGCHEONGNAMDO, value: '충남', search: '충청남도' },
  { key: PROVINCE_TYPE.DAEJEON, value: '대전', search: '대전' },
  { key: PROVINCE_TYPE.SEJONG, value: '세종', search: '세종' },
  { key: PROVINCE_TYPE.JEOLLABUKDO, value: '전북', search: '전라북도' },
  { key: PROVINCE_TYPE.JEOLLANAMDO, value: '전남', search: '전라남도' },
  { key: PROVINCE_TYPE.GWANGJU, value: '광주', search: '광주' },
  { key: PROVINCE_TYPE.GYEONGSANGBUKDO, value: '경북', search: '경상북도' },
  { key: PROVINCE_TYPE.GYEONGSANGNAMDO, value: '경남', search: '경상남도' },
  { key: PROVINCE_TYPE.BUSAN, value: '부산', search: '부산' },
  { key: PROVINCE_TYPE.DAEGU, value: '대구', search: '대구' },
  { key: PROVINCE_TYPE.ULSAN, value: '울산', search: '울산' },
  { key: PROVINCE_TYPE.JEJU, value: '제주', search: '제주' },
];
